upstream myblog_backend {
    server 127.0.0.1:8080;
}

upstream myblog_minio {
    server 127.0.0.1:9000;
}

server {
    listen 80;
    server_name example.com;

    root /var/www/blog;
    index index.html;
    client_max_body_size 100m;

    location = /admin {
        return 301 /admin/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://myblog_backend/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        alias /var/www/admin/;
        index index.html;
        try_files $uri $uri/ /admin/index.html;
    }

    location /files/ {
        proxy_pass http://myblog_minio/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
